name = "cart-game-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "cart-game-db"
database_id = "55bc4177-4d0b-40ad-b12c-75ea0526d4e9"

[vars]